import { Router } from 'express';

import DefaultRouter from '../../../modules/status/infra/http/routes/default.route.js';
import AccountingRouter from '../../../modules/product/infra/http/routes/accounting.router.js';
import AttendanceRouter from '../../../modules/product/infra/http/routes/attendance.router.js';
import ChatRouter from '../../../modules/product/infra/http/routes/chat.router.js';
import ClassSectionRouter from '../../../modules/product/infra/http/routes/class-section.router.js';
import ExamRouter from '../../../modules/product/infra/http/routes/exam.router.js';
import InstituteCouter from '../../../modules/product/infra/http/routes/insitute.router.js';
import InvoicingRouter from '../../../modules/product/infra/http/routes/invoicing.router.js';
import MasterRouter from '../../../modules/product/infra/http/routes/master.router.js';
import ParentRouter from '../../../modules/product/infra/http/routes/parent.route.js';
import PaymentRouter from '../../../modules/product/infra/http/routes/payment.router.js';
import SalaryRouter from '../../../modules/product/infra/http/routes/salary.router.js';
import StaffAccRouter from '../../../modules/product/infra/http/routes/staffAcc.route.js';
import StudentRouter from '../../../modules/product/infra/http/routes/student.router.js';
import SubjectRouter from '../../../modules/product/infra/http/routes/subject.router.js';
import TransportRouter from '../../../modules/product/infra/http/routes/transport.route.js';
import UserRouter from '../../../modules/product/infra/http/routes/user.router.js';

const Routes = Router();
Routes.use('/', DefaultRouter);
Routes.use("/master", MasterRouter);
Routes.use("/user", UserRouter);
Routes.use("/institute", InstituteCouter);
Routes.use("/transportRoute", TransportRouter);
Routes.use("/class-sections", ClassSectionRouter);
Routes.use("/student", StudentRouter);
Routes.use("/staff-acc", StaffAccRouter);
Routes.use("/parent", ParentRouter);
Routes.use("/subjects", SubjectRouter);
Routes.use("/attendance", AttendanceRouter);
Routes.use("/accounting", AccountingRouter);
Routes.use("/salary", SalaryRouter);
Routes.use("/exam", ExamRouter);
Routes.use("/chat", ChatRouter);
Routes.use("/payment", PaymentRouter);
Routes.use("/invoicing", InvoicingRouter);
export default Routes;
