import { Router } from "express";
import { studentControllerInstance } from '../controllers';

const StudentRouter = Router();
StudentRouter.post("/submitApplicationForm", studentControllerInstance.submitApplicationForm);
StudentRouter.post("/createStudent", studentControllerInstance.createStudent);
StudentRouter.post("/bulkLoadStudents", studentControllerInstance.bulkLoadStudents);
StudentRouter.post("/transferStudentCampus", studentControllerInstance.transferStudentCampus);
StudentRouter.post("/promoteStudent", studentControllerInstance.promoteStudent);
StudentRouter.get("/getAllStudents/:campusId", studentControllerInstance.getAllStudents);
StudentRouter.get("/getAllStudentsByClassAndSection/:campusId/:classId/:sectionId/:active", studentControllerInstance.getAllStudentsByClassAndSection);
StudentRouter.get("/getStudentById/:id/:campusId", studentControllerInstance.getStudentId);
StudentRouter.post("/updatePhoto/:campusId/:id", studentControllerInstance.updatePhoto);

StudentRouter.delete("/deleteStudent/:id/:campusId", studentControllerInstance.deleteStudent);
StudentRouter.get("/getStudentBirthday/:campusId", studentControllerInstance.getStudentBirthday);
StudentRouter.get("/getAllAdmissionEnquiry/:campusId/:isFromApp", studentControllerInstance.getAllAdmissionEnquiry);
StudentRouter.post("/createAdmissionInquiry", studentControllerInstance.createAdmissionInquiry);
StudentRouter.post("/approveAdmissionInquiry", studentControllerInstance.approveAdmissionInquiry);
StudentRouter.get("/deleteAdmissionEnquiry/:campusId/:id/:currentUserid", studentControllerInstance.deleteAdmissionEnquiry);
StudentRouter.get("/fetchAdmissionFormStats/:campusId", studentControllerInstance.fetchAdmissionFormStats);
StudentRouter.post("/updateStudent/:campusId/:id", studentControllerInstance.updateStudent);
StudentRouter.get("/getStudingRatingAndComments/:campusId/:classId/:sectionId/:userId", studentControllerInstance.getStudingRatingAndComments);
StudentRouter.get("/getStudentNotes/:campusId/:classId/:sectionId/:userId", studentControllerInstance.getStudentNotes);
StudentRouter.delete("/deleteDailyNote/:id/:campusId", studentControllerInstance.deleteDailyNote);
StudentRouter.delete("/deleteStudentReward/:id/:userId", studentControllerInstance.deleteStudentReward);
StudentRouter.delete("/deleteStudentBehavior/:id/:userId", studentControllerInstance.deleteStudentBehavior);
StudentRouter.delete("/deleteStudentExtracurricular/:id/:userId", studentControllerInstance.deleteStudentExtracurricular);
StudentRouter.post("/bulkSaveStudentCompetition", studentControllerInstance.bulkSaveStudentCompetition);
StudentRouter.delete("/deleteStudentCompetition/:id/:userId", studentControllerInstance.deleteStudentCompetition);
StudentRouter.post("/updateStudentCompetition", studentControllerInstance.updateStudentCompetition);
StudentRouter.post("/updateStudentExtracurricular", studentControllerInstance.updateStudentExtracurricular);
StudentRouter.post("/saveStudentDailyNotes", studentControllerInstance.saveStudentDailyNotes);
StudentRouter.post("/saveStudentRating", studentControllerInstance.saveStudentRating);
StudentRouter.delete("/deleteRating/:id/:campusId", studentControllerInstance.deleteRating);
StudentRouter.post("/getStudentsByStudentPatialNameOrId", studentControllerInstance.getStudentsByStudentPatialNameOrId);
StudentRouter.get("/getStudentHistoryByIdAndSession/:userId/:sessionId", studentControllerInstance.getStudentHistoryByIdAndSession);
export default StudentRouter;