{
 "title": "Admin Home Screen Dashboard",
 "description": "MySkoolReports",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "userId", "label": "User ID" },
   { "name": "campusId", "label": "Campus ID" }
  ]
 },
 "panels": [
  {
   "title": "Select a class for timetable",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "metabase" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "dataset": "metabase", "rawSql": "select * from myskool.Holidays" }
   ]
  },
  {
   "title": "Selected Campus",
   "type": "stat",
   "description": "Displaying current selected campus",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "select * from Campus where id = $campusId "
    }
   ]
  },
  { "title": "User Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Users by Type",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT COUNT(id),userType  FROM User \nwhere campusId=$campusId \nGROUP BY userType "
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current Session",
   "type": "stat",
   "description": "Displaying selected session for the organization",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "SELECT sess.session FROM Institute  inst\nleft join Sessions sess ON sess.id = inst.sessionId"
    }
   ]
  },
  {
   "title": "Unpaid Invoices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT COUNT(*) FROM MYAALInvoices where feeStatus NOT IN ('Paid','Cancelled');"
    }
   ]
  },
  {
   "title": "Unpaid Amount",
   "type": "gauge",
   "description": "Total unpaid amount from invoices",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT SUM(AMOUNT) FROM MYAALInvoices where feeStatus IN ('Unpaid','Partial');"
    }
   ]
  },
  {
   "title": "Income Today",
   "type": "gauge",
   "description": "Total income today, constitutes fee payment, pre payment, inventory sell etc",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select SUM(AMOUNT) FROM Transactions where transactionType='Credit' and DATE(created_at) = CURDATE()"
    }
   ]
  },
  {
   "title": "Expense Today",
   "type": "gauge",
   "description": "Sum of all debits including Salary Payment, Purchases etc",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' and DATE(created_at) = CURDATE()"
    }
   ]
  },
  {
   "title": "Profit Today",
   "type": "gauge",
   "description": "Difference of Income & Expense",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT\n    (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Credit' and DATE(created_at) = CURDATE())\n  - (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' and DATE(created_at) = CURDATE()) AS Difference"
    }
   ]
  },
  {
   "title": "Expense this month",
   "type": "gauge",
   "description": "Total expense for this month",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' and MONTH(created_at) = MONTH(CURRENT_DATE())\nAND YEAR(created_at) = YEAR(CURRENT_DATE())"
    }
   ]
  },
  {
   "title": "Income this month",
   "type": "gauge",
   "description": "Total income for this month",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select SUM(AMOUNT) FROM Transactions where transactionType='Credit' and MONTH(created_at) = MONTH(CURRENT_DATE())\nAND YEAR(created_at) = YEAR(CURRENT_DATE())"
    }
   ]
  },
  {
   "title": "Profit this month",
   "type": "gauge",
   "description": "Difference of Income & Expense for this month",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT\n    (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Credit' and MONTH(created_at) = MONTH(CURRENT_DATE())\nAND YEAR(created_at) = YEAR(CURRENT_DATE()))\n  - (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' and MONTH(created_at) = MONTH(CURRENT_DATE())\nAND YEAR(created_at) = YEAR(CURRENT_DATE())) AS Difference"
    }
   ]
  },
  {
   "title": "Income this Year",
   "type": "gauge",
   "description": "Total income this year, constitutes fee payment, pre payment, inventory sell etc",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select SUM(AMOUNT) FROM Transactions where transactionType='Credit' and YEAR(created_at) = YEAR(CURRENT_DATE())"
    }
   ]
  },
  {
   "title": "Expense this Year",
   "type": "gauge",
   "description": "Sum of all debits including Salary Payment, Purchases etc",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' and YEAR(created_at) = YEAR(CURRENT_DATE())"
    }
   ]
  },
  {
   "title": "Profit this Year",
   "type": "gauge",
   "description": "Difference of Income & Expense for this year",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "myskool",
     "rawSql": "SELECT\n    (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Credit' AND YEAR(created_at) = YEAR(CURRENT_DATE()))\n  - (select IFNULL(SUM(AMOUNT),0) FROM Transactions where transactionType='Debit' AND YEAR(created_at) = YEAR(CURRENT_DATE())) AS Difference"
    }
   ]
  },
  {
   "title": "Expense Trend Per Month",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "select SUM(amount), LAG(SUM(amount)) OVER (ORDER BY MONTH(created_at)) AS previous_value,\nMONTH(created_at) from myskool.Transactions where transactionType='Debit'\nAND YEAR(created_at) = YEAR(CURRENT_DATE()) \nAND campusId=$campusId \ngroup by MONTH(created_at)  \norder by MONTH(created_at)  desc\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Income Trend",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 37 },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "select SUM(amount), LAG(SUM(amount)) OVER (ORDER BY MONTH(created_at)) AS previous_value,\nMONTH(created_at) from myskool.Transactions where transactionType='Credit'\nAND YEAR(created_at) = YEAR(CURRENT_DATE()) \nAND campusId=$campusId \ngroup by MONTH(created_at)  \norder by MONTH(created_at)  desc\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Recent Paid Fees",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "SELECT invoiceNumber as 'Invoice#',paidOn as 'Paid On',paymentType as 'Paid In',dueDate as 'Due on',amount as 'Amount' FROM MYAALInvoices\nwhere feeStatus IN ('Paid','Partial')\nAND campusId=$campusId \norder by paidOn desc LIMIT 3;"
    }
   ]
  },
  {
   "title": "Invoices Past Due",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "SELECT amount as 'Amount', usr.displayName as 'Student',cls.className as 'Class', sec.sectionName as 'Section', invoiceNumber as 'Invoice#',\ndueDate as 'Due on'FROM myskool.MYAALInvoices inv\nLEFT JOIN myskool.Class cls ON cls.id=inv.classId\nLEFT JOIN myskool.Section sec ON sec.id=inv.sectionId\nLEFT JOIN myskool.User usr ON usr.id=inv.userId\nwhere inv.feeStatus IN ('Unpaid','Partial')\nAND inv.campusId=$campusId AND inv.dueDate<curdate()\norder by inv.paidOn LIMIT 3;"
    }
   ]
  },
  {
   "title": "Top Unpaid Fees",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "metabase",
     "rawSql": "SELECT invoiceNumber as 'Invoice#',dueDate as 'Due on',amount as 'Amount' FROM myskool.MYAALInvoices\nwhere feeStatus IN ('Unpaid','Partial')\nAND campusId=$campusId \norder by paidOn LIMIT 3;"
    }
   ]
  },
  {
   "title": "Admissions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Admissions",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 41 },
     "options": {
      "content": "<div style=\"display: flex;justify-content: space-between;text-align:center\">\n  {{#each data}}\n  <div style=\"display:inline-block;text-align:center\">\n    <img src=\"{{Photo}}\"\n        alt=\"Avatar\"\n        style=\"vertical-align: middle;\n        text-align:center;\n        width: 100px;\n        height: 100px;\n        border-radius: 50%;\"/>\n      <p style=\"font-weight:600;text-align:center;\">{{Name}}</p>\n      <div style=\"display: flex;justify-content: middle;text-align:center\">\n        <p style=\"font-weight:400;text-align:center; color:red\">{{Class}}</p>\n        -\n        <p style=\"font-weight:400;text-align:center; color:red\">{{Section}}</p>\n      </div>\n</div>\n{{/each}}\n<div>"
     },
     "targets": [
      {
       "dataset": "metabase",
       "rawSql": "select usr.displayName as 'Name',cls.className as 'Class', sec.sectionName as 'Section',usr.thumbnailUrl as'Photo'\n,usr.admissionDate from myskool.User usr\nLEFT JOIN myskool.Class cls ON cls.id=usr.classId\nLEFT JOIN myskool.Section sec ON sec.id=usr.sectionId\nwhere usr.userType='student' and usr.active=1\norder by usr.admissionDate desc\nLimit 3"
      }
     ]
    }
   ]
  },
  {
   "title": "Accounting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Month wise Income Overview",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "dataset": "myskool",
       "rawSql": "SELECT MONTHNAME(created_at), SUM(AMOUNT) FROM Transactions where transactionType='Credit' \nAND YEAR(created_at) = YEAR(CURRENT_DATE()) and campusId = $campusId \ngroup by MONTHNAME(created_at);"
      }
     ]
    },
    {
     "title": "Month wise Expense Overview",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "dataset": "myskool",
       "rawSql": "SELECT MONTHNAME(created_at), SUM(AMOUNT) FROM myskool.Transactions where transactionType='Debit' \nAND YEAR(created_at) = YEAR(CURRENT_DATE()) and campusId = $campusId \ngroup by MONTHNAME(created_at);"
      }
     ]
    },
    {
     "title": "Month wise unpaid fees amount w/t count",
     "type": "barchart",
     "description": "Hover on the bars to see the Class, Section and Count of pending fees",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "dataset": "metabase",
       "rawSql": "SELECT MONTHNAME(inv.created_at),cls.className, sec.sectionName, SUM(AMOUNT), COUNT(*) FROM myskool.MYAALInvoices inv\nLEFT JOIN myskool.Class cls ON cls.id = inv.classId\nLEFT JOIN myskool.Section sec ON sec.id = inv.sectionId\nwhere inv.feeStatus IN ('Unpaid', 'Partial') \nAND YEAR(inv.created_at) = YEAR(CURRENT_DATE()) and inv.campusId = $campusId \ngroup by MONTHNAME(inv.created_at),cls.className, sec.sectionName;"
      }
     ]
    }
   ]
  },
  { "title": "Attendance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Calendar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Holidays",
     "type": "marcusolsson-calendar-panel",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "dataset": "myskool",
       "rawSql": "SELECT holi.name, holi.holidayStart, holi.holidayEnd,cls.className,sec.sectionName FROM Holidays holi\nLEFT JOIN Class cls ON cls.id = holi.classId\nLEFT JOIN Section sec ON sec.id = holi.sectionId\nwhere holi.campusId=$campusId "
      }
     ]
    }
   ]
  }
 ]
}