-- CreateTable
CREATE TABLE `BehaviourLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `teacherId` INTEGER NOT NULL,
    `category` ENUM('ATTENTION', 'CLASS_PARTICIPATION', 'HOMEWORK', 'WORK_HABITS', 'LEARNING_SKILLS', 'ORGANIZATION', 'COMPLETES_TASKS_ON_TIME', 'FOLLOWS_INSTRUCTIONS', 'PUNCTUALITY', 'DISCIPLINE', 'ATTENDANCE', 'UNIFORM', 'CLEANLINESS', 'COURTESY', 'RESPECT', 'BEHAVIOUR_WITH_TEACHERS', 'BEHAVIOUR_WITH_PEERS', 'SCHOOL_PROPERTY_CARE', 'RULES_COMPLIANCE', 'COMMUNICATION_SKILLS', 'TEAMWORK', 'COOPERATION', 'SOCIAL_SKILLS', 'EMPATHY', 'CONFLICT_RESOLUTION', 'LEADERSHIP', 'INITIATIVE', 'ADAPTABILITY', 'CONFIDENCE', 'RESPONSIBILITY', 'SELF_CONTROL', 'SELF_MOTIVATION', 'ATTITUDE', 'PERSEVERANCE', 'PROBLEM_SOLVING', 'CREATIVITY', 'CRITICAL_THINKING', 'DECISION_MAKING', 'TIME_MANAGEMENT', 'GOAL_SETTING') NULL,
    `points` INTEGER NOT NULL,
    `note` VARCHAR(191) NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `created_by` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BehaviourLog` ADD CONSTRAINT `BehaviourLog_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BehaviourLog` ADD CONSTRAINT `BehaviourLog_teacherId_fkey` FOREIGN KEY (`teacherId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
